spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank_base
    hikari:
      username: root
      password: 123456

server:
  port: 9009

logging:
  level:
    com.example.springdemo.mapper: debug