spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank_base
    hikari:
      username: root
      password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 5000
      database: 0

server:
  port: 9009
  jetty:
    threads:
      max: 200

logging:
  level:
    com.kevin.bankmanagementsys.BankManagementSysApplication: debug